export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

//group
export const LOAD_GROUPS = 'LOAD_GROUPS';
export const LOADING_GROUPS = 'LOADING_GROUPS';

// Group create
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL';
export const GET_USER_CREATED_GROUPS = 'GET_USER_CREATED_GROUPS';
export const GET_USER_CREATED_GROUPS_CHECK = 'GET_USER_CREATED_GROUPS_CHECK';




